version: 0.0.00
name: 'Roll Groups'
module:
    name: 'Roll Groups'
    description: 'Allows users to view a listing of roll groups'
    entryURL: list
    type: Core
    active: 'Y'
    category: People
    version: 0.0.00
    author: 'Craig Rayner'
    url: 'http://www.craigrayner.com'
    actions:
        'Manage Roll Groups':
            name: 'Manage Roll Groups'
            precedence: 0
            category: 'Roll Groups'
            description: ''
            URLList: 'manage,edit,add,delete'
            entryURL: manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'View Roll Groups':
            name: 'View Roll Groups'
            precedence: 1
            category: 'Roll Groups'
            description: 'View a brief profile of roll groups in school.'
            URLList: 'list,details'
            entryURL: list
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'Y'
            defaultPermissionStudent: 'Y'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'Y'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'Y'
            categoryPermissionParent: 'Y'
            categoryPermissionOther: 'Y'
            permissions:
                - Administrator
                - Student
                - 'Support Staff'
                - Teacher
                - Parent
                - Librarian
