CREATE TABLE `__prefix__RollGroup` (
  `id` int(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `nameShort` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `attendance` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y',
  `website` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `academic_year` int(3) UNSIGNED ZEROFILL DEFAULT NULL,
  `tutor1` int(10) UNSIGNED ZEROFILL DEFAULT NULL,
  `tutor2` int(10) UNSIGNED ZEROFILL DEFAULT NULL,
  `tutor3` int(10) UNSIGNED ZEROFILL DEFAULT NULL,
  `assistant1` int(10) UNSIGNED ZEROFILL DEFAULT NULL,
  `assistant2` int(10) UNSIGNED ZEROFILL DEFAULT NULL,
  `assistant3` int(10) UNSIGNED ZEROFILL DEFAULT NULL,
  `facility` int(10) UNSIGNED ZEROFILL DEFAULT NULL,
  `next_roll_group` int(5) UNSIGNED ZEROFILL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nameAcademicYear` (`name`,`academic_year`),
  UNIQUE KEY `abbrAcademicYear` (`nameShort`,`academic_year`),
  UNIQUE KEY `tutor1AcademicYear` (`tutor1`,`academic_year`),
  KEY `academicYear` (`academic_year`),
  KEY `tutor1` (`tutor1`),
  KEY `tutor2` (`tutor2`),
  KEY `tutor3` (`tutor3`),
  KEY `assistant1` (`assistant1`),
  KEY `assistant2` (`assistant2`),
  KEY `assistant3` (`assistant3`),
  KEY `facility` (`facility`),
  KEY `nextRollGroup` (`next_roll_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT = 1;
